controller/client/http.go
This is shamelessly ported directly from @bacongobbler's deis/deis#5013.
This PR improves the resultant client error message they get when the returned response is incorrect. This is especially important for determining the error message
Old message when using a v2 client with a v1 cluster:
```
http://deis.10.245.1.3.xip.io does not appear to be a valid Deis controller. Make sure that the
Controller URI is correct and the server is running.
```
New message:
```
http://deis.10.245.1.3.xip.io/v2/ does not appear to be a valid Deis controller. Make sure that the
Controller URI is correct and the server is running.
```
Notice the appended /v2/ path, which users can assume this is a v2 client.
=> ref(http.go): improve client error message

Makefile
Includes [version 0.10.1](https://github.com/Masterminds/glide/releases/tag/0.10.1) of the `glide` package manager, among other updates to the standard Go developer support image.
=> chore(Makefile): update docker-go-dev to 0.10.0

README.md
The other component repos all list their "download" (Docker registry) link last:
[![Build Status](https://travis-ci.org/deis/minio.svg?branch=master)](https://travis-ci.org/deis/minio) [![Go Report Card](http://goreportcard.com/badge/deis/minio)](http://goreportcard.com/report/deis/minio) [![Docker Repository on Quay](https://quay.io/repository/deisci/minio/status "Docker Repository on Quay")](https://quay.io/repository/deisci/minio)
This improves consistency by moving the bintray download badge last.
=> style(README.md): move download badge last for consistency

cmd/apps.go
Django Rest Framework will wrap the string with quotes because
of the JSONRenderer. Django's HttpResponse class handles the
application logs as we expect it to. This change reflects the
change in the controller to split logs properly by the newline
character.
port of deis/deis#5004
to be tested with deis/controller#592
=> fix(controller): use django HttpResponse for logs

pkg/git/git.go, pkg/git/git_test.go
This transitions the CLI from creating git `deis` git remotes that use the same hostname as the controller to using one with a hostname _derived_ from the controller's hostname.
This is to support the contingency wherein some scenario has forced an admin to use _two_ different load balancers-- one for builder and another for everything else.
See https://github.com/deis/controller/issues/657 for further context.
=> chore(git): Make builder git remote use different hostname

cmd/apps.go
=> fix(cmd): strip printLogs with only one newline

cmd/registry.go, cmd/registry_test.go
If the value contains an equals sign, the parsing logic fails.
=> fix(cmd): split only twice at most

cmd/registry.go, cmd/registry_test.go, parser/registry.go
related to deis/workflow#239. Also increases test coverage around this so a user cannot accidentally fat-finger an invalid key.
=> ref(cmd): clarify deis registry usage

README.md
this is a quick PR to unblock #71. We cannot re-run any travis builds because the pull requests no longer exist.
Alternatively I can also do a `git commit --allow-empty` to bump the build, but I figured a PR would be best.
closes #71 
closes deis/workflow#282
=> doc(README): link to LICENSE

version/version.go
DO NOT MERGE until we are ready to release 2.0.0. Just bumping this to close #70.
=> chore(version): bump client version to 2.0.0

parser/limits.go
kubernetes supports either whole CPUs or a thousandth of a CPU using milli units.
closes deis/controller#786
=> doc(parser): update the CPU limit docstring

cmd/apps.go
Fixes #69 
Ideally we would direct individual lines to STDOUT and STDERR based on what the command itself does... however, the kubernetes api does not distinguish between the STDOUT and STDERR, so I'm not sure that is possible. I think this is probably the best we can do until we get interactive run sessions implemented.
=> feat(apps): print output from command to stderr if the command failed

README.md
They changed their badge location and it is currently broken.
=> fix(README): fix go report card badge

cmd/ps.go
The client side and server side checks for valid process names were different, so each would accept different names. This updated the client to use the [regexp as the controller](https://github.com/deis/controller/blob/master/rootfs/api/serializers.py#L15-L17)
Fixes #88
=> fix(ps): match controller regexp for ps names

README.md
I overlooked a windows support message and a typo.
=> docs(README): fix some windows links in the README

cmd/config.go, cmd/healthchecks.go, deis.go, glide.lock, parser/healthchecks.go, parser/utils.go, parser/utils_test.go
This is the client-side implementation for deis/workflow#322.
TODO:
depends on https://github.com/deis/controller-sdk-go/pull/10
=> feat(deis.go): implement `deis healthchecks` client commands

.travis.yml
This cache directory was useful when glide was slow downloading k8s.io/kubernetes, but updates have
made fetches significantly quicker. The cache has been recently giving us more headaches with the
new SDK, so removing this should make builds more reliable again.
=> ref(travis): remove vendor cache

.gitignore, glide.yaml
This patch also updates the `.gitignore` to exclude host-built binaries (built with `go build`)
=> fix(glide.yaml): pin the SDK version

.travis.yml
Right now, we have no CI builds for releases, including `v2.1`.
=> fix(ci): build tags so that tagged commits are uploaded

cli/cli.go, cmd/shortcuts.go, deis.go, parser/shortcuts.go
This used to be a CLI command, but was lost in the great Go client refactor way back in Deis v1. We still reference it in `deis help` though.
=> feat(deis): add `deis shortcuts` command

cmd/ps.go
Deployments created a different pod name then what RCs do (we have less flexibility): oddest-lungfish-cmd-1269180282-60byi
This way we know the proc type is always at the front of the slice, after replacing the app name
=> fix(ps): restarting a single pod created by Deployments was not working

Jenkinsfile
Jenkins checks out the exact commit, not the branch, which broke the previous method.
=> fix(Jenkinsfile): lookup branch from commit SHA

Jenkinsfile
Sorry to keep doing this, I haven't been able to trigger these code paths and fully test them until they are merged to master.
It seems like a newline is added when reading or writing to the file, throwing off the string comparison, so I'm stripping it.
=> fix(CI): strip whitespace from file read

glide.lock, glide.yaml
The merge of https://github.com/deis/controller-sdk-go/pull/38 includes the ability to determine whether a REST API call to the controller failed or succeeded but with an API version incompatibility. This patch uses that new SDK version.
Clients built from this patch now can register (and perform operations) on controller API instances with differing API versions. See the below console output, paying special attention to the non-empty (but redacted) token.
```console
ENG000656:workflow-cli aaronschlesinger$ ./deis register deis.104.197.169.110.nip.io
!    WARNING: Client and server API versions do not match. Please consider upgrading.
!    Client version: 2.0
!    Server version: 2.1
username: arschles
password: 
password (confirm): 
email: arschles@gmail.com
!    WARNING: Client and …
```
=> fix(glide.lock,glide.yaml): update SDK version

Makefile
See https://github.com/deis/docker-go-dev/releases/tag/0.14.0
=> chore(Makefile): use latest go-dev and glide

cmd/ps.go, cmd/ps_test.go
Output before:
```
keerthanmala$ deis scale web=-1
'web=-1' does not match the pattern 'type=num', ex: web=2
Scaling processes... but first, coffee!
done in 0s
=== woodsy-jokester Processes
--- cmd:
woodsy-jokester-v2-cmd-zbonf up (v2)
```
after:
```
deis scale web=-1 -a=woodsy-jokester
'web=-1' does not match the pattern 'type=num', ex: web=2
```
=> fix(scale):dont call controller if there is no valid scale pattern

Jenkinsfile
if this pipeline is triggered by a PR in controller-sdk-go
Ref https://github.com/deis/controller-sdk-go/issues/39
Ref https://github.com/deis/controller-sdk-go/pull/41
=> feat(Jenkinsfile): receive sdk-related params

cmd/colors_unix.go
Fixes #66 by reserving a color for controller log messages.
=> feat(colors): reserve magenta for controller log messages

Jenkinsfile
As the `checkout scm` step in the `Build artifacts` stage
may produce a different merge commit sha from the previous
`Git Info` stage (which sets `git_commit`).  Therefore, since we
are passing down `git_commit` to e2e job, we need to build artifact
with this value.
(Example of behavior can be seen in the following pipeline run https://ci.deis.io/job/Deis/job/workflow-cli/job/PR-110/17/console)
cc @Joshua-Anderson
=> fix(Jenkinsfile): set VERSION to git_commit

cmd/auth.go, glide.lock, glide.yaml, parser/auth.go
=> feat(cmd): add auth:whoami --all

cmd/apps.go, cmd/apps_test.go
Previously, we took a very naive approach to determining the app url. We did appID**~~deis~~**.cluster.com
This approach has a problem however, because you can assign subdomains to an app that mask another app:
```console
$ deis domains:add a -a t
$ deis apps:create a --no-remote
$ deis apps:open -a a # opens a.cluster.com, which actually points to t
```
Now, `apps:open` and `apps:info` use the app's first domain, usually the one that is assigned by default. If the app doesn't have any domains, like `a` in the example does, it'll print that the app doesn't have any domains.
This also allows me to remove `api.Apps.URL` from the SDK laster, removing the naive behavior in a way that doesn't break anything.
=> bug(cmd): add more advanced handling of app urls

Makefile
The CLI is now built with go1.6 and docker-go-dev is using v1.6, so I don't think there's any reason to keep it around.
=> ref(makefile): remove GO15VENDOREXPERIMENT as it is no longer necessary

Jenkinsfile, Makefile
This fixes with jenkins failing to delete files when cleaning up.
=> fix(tests): set owner of files created by containers to the local user

Jenkinsfile, Makefile
I'm not going to go into details publicly, but I realized there are ways for untrusted users to access the GCS credentials.
=> fix(CI): don't allow untrusted commands when uploading

pkg/git/git.go
The `git` PR was merged at the same time as the new linting PR and somehow passed CI without running through the new linter.
=> fix(git): fix linting error

Jenkinsfile
I've noticed this behavior earlier with the gcs closure, but it seemed to work otherwise, so I left it elsewhere.
@jchauncey noticed https://ci.deis.io/job/Deis/job/workflow-cli/job/master/69/console, which indicated that e2e tests would restart until the passed, indicating that false was not working.
=> fix(CI): False doesn't abort build

Jenkinsfile
The false was accidentally removed from the loop, preventing it from looping.
=> fix(CI): add false to retry loop

Jenkinsfile, Makefile, parser/version.go, settings/settings.go, version/version.go
If commit is not a tagged commit: `<latest tag>-<sha>`.
If commit is tagged `<tag>`
If version is overridden with `$VERSION`, `<version>`
cc @vdice
This way we no longer have to manually bump the version in code.
=> fix(version): move all version logic to git

cmd/routing.go, deis.go, glide.lock, glide.yaml, parser/routing.go
This command enables or disables the application being exposed external to the cluster through the
router.
see https://github.com/deis/controller/pull/934
SDK changes: https://github.com/deis/controller-sdk-go/compare/09f8465bf5598f84987734082d22f4201632a320...cd0f563b127736127e0e9debeddcbcb014621b04
=> feat(cmd): add deis routing

settings/settings.go, settings/settings_test.go
the workflow-cli version is defined based on the git tag which already
has a prepended v (v2.4.0) resulting in the user agent seen below
"GET /v2/apps/foo/pods/?limit=100 HTTP/1.1" 200 593 "Deis Client vv2.4.0"
Fixes #186
=> fix(settings): remove duplicated 'v' in user agent

.dockerignore, cmd/config.go, cmd/config_test.go
I'm skipping `config:push` and `config:pull` at this moment, because they're going to more complicated since they depend on pipes `>` and `<` for input and output.
=> tests(config): add test for config commands

cmd/git.go, pkg/git/git.go
Log the command and the Stderr that results in an git error:
```
$ deis git:remote -a test
Error: Error when running 'git remote add deis ssh://git@deis-builder.1.1.1.1.nip.io:2222/test.git'
fatal: Not a git repository (or any of the parent directories): .git
```
=> fix(git): properly log errors from git

cmd/ps.go, glide.lock, glide.yaml
Since iterating over a hash is random, it resulted in random ordering and occasionally broke tests.
=> fix(ps): use new sdk for sorted processes

parser/limits.go
It conflicts with the global short config flag
=> fix(limits): remove short cpu flag

.dockerignore, Jenkinsfile, Makefile
Switch to building within the dockerfile as well.
This also excludes unneeded files from the container, so the `COPY` step at the end remains fast.
On my macbook a cached containerized `make build` takes the same amount of time as a `go build` on the host machine.
This also slims up test images, hopefully speeding up CI.
Another bonus: No more, "did you run `make glideup`". Dockers caching system will automatically download new dependencies when they change.
⚠️ the deis binary is now saved to `_dist/deis` so that you don't have to mount the entire working directory into the docker container.
=> feat(Makefile): build using dockefile and slim image size

Makefile
To upload/overwrite the `deis-stable-*` binaries on each release, in a similar manner as we do for `latest`/master commits.
(Not tied to the keyword `stable` and open to suggestions for better naming)
TODO
cc @Joshua-Anderson
=> feat(Makefile): add build-stable target

cmd/users.go, cmd/users_test.go, parser/users.go
Also added tests to cover the behavior
This will probably break e2e, but I'm questioning the need for `users:list` e2e tests. It's tested in the controller, the sdk, and cli, so as long as the api contract stays the same (which we commit to by using semver) it should work.
=> feat(users): show admins when listing users

cmd/cmd.go, cmd/version.go, cmd/version_test.go, deis.go, parser/version.go
Fixes #25 
I'm not including `client.ControllerVersion` because it's not what it seems to be. It's the untruncated API version string. This is not the same as the deis platform version or the controller image version, so it would just confuse people.
=> feat(version): add deis version --all

cmd/apps.go, cmd/apps_test.go, cmd/git.go, cmd/perms.go, cmd/utils.go, cmd/utils_test.go, pkg/git/git.go, pkg/git/git_test.go
Removes duplicate `git remote -v` logic, and removes `git get-url` fixing #196.
=> feat(git): clean up git package and write tests

cmd/apps_test.go, cmd/builds_test.go, cmd/certs_test.go, cmd/domains_test.go, cmd/keys_test.go, cmd/perms_test.go, cmd/releases_test.go, cmd/users_test.go
Fixes deis/workflow-e2e#196
Fixes deis/workflow-e2e#198
Fixes deis/workflow-e2e#199
Fixes deis/workflow-e2e#200
Fixes deis/workflow-e2e#201
=> Limit tests

Dockerfile
See https://github.com/golang/go/issues?q=milestone%3AGo1.7.1
and https://github.com/deis/docker-go-dev/releases/tag/0.17.1
Closes #240.
=> chore(Dockerfile): update go-dev and go toolchain

Jenkinsfile
Running these tasks serially works around an apparent race condition bug whereby upload to codecov.io was tried twice, and failed.
=> fix(Jenkinsfile): un-parallelize lint and test tasks

settings/settings.go
Settings files contain auth tokens and should not be world-readable.
=> fix(perms): user-only settings file perms

README.md, deis.go, deis_test.go
**Ported from V1: https://github.com/deis/deis/pull/5099.**
---
We have a private PaaS with multiple Deis clusters (staging + two productions at the moment). We have also a tool that allows us to manage all clusters from a single web panel. It also connects other APIs such as servers provider and DNS provider. As the result we can perform actions that touches many parts of the system (for example create DNS records for all Deis workers and make CNAME to use with `DEISCTL_TUNNEL` or create a database and assign `DATABASE_URL` for a given application). We have also created plugins to extend Deis CLI. For example there is a support for database (+backups) management and easy SSH access for our developers.
We have `deis backups:[create|show|restore|list]` commands and we want to show usage …
=> fix(deis.go): do not add top level command to cmdArgs

cmd/cmd.go, cmd/keys.go, cmd/keys_test.go, parser/keys.go, parser/keys_test.go
This arg can be used interchangably with the key arg to keep backwards compatibility
That allows a user to do `deis keys:add ~/.ssh/secret.pub` and the name is detected or `keys:add magic ~/.ssh/magic.pub` or `deis keys:add travis` and then get the choice list to pick from
Closes #256
=> feat(keys): add an optional name support for keys:add

pkg/ssh/ssh.go, pkg/ssh/ssh_test.go
Updated the SSH parser regex to allow for [ed25519 SSH keys](http://ed25519.cr.yp.to/). Also added (very simple) test for key that would fail the regex. 
I develop in other languages but this is the very first golang code I've ever written, so very open to any nits you may have.
=> fix(ssh): support ed25519 SSH keys

parser/auth.go
Changes the `--ssl-verify` default from `false` to `true` on both the `auth:login` and `auth:register` actions. This change should be backwards compatible with clusters using HTTP (since no SSL verification is performed) and clusters with valid SSL setups. Previously created profiles for clusters with invalid or self-signed certificates should continue to work, but new ones will require an explicit `--ssl-verify false` flag to be passed on register and login.
See discussion on #264
=> feat(auth): change --ssl-verify default to true

cmd/limits.go, cmd/limits_test.go, parser/limits.go, parser/limits_test.go
Accept new cli format limits:set web=500m/2000m
Value is map to requests/limits parameter in Kubernetes resource management.
See https://github.com/deis/workflow/issues/562
e2e https://github.com/deis/workflow-e2e/pull/335
Requires https://github.com/deis/controller/pull/1118
=> feat(limits-cmd): accept new limits:set value type

cmd/auth.go, cmd/auth_test.go, parser/auth.go, parser/auth_test.go
This flag allows users to enable/disable automatic login after registering a user.
closes #266
=> feat(parser): add --login=true to auth:register

cmd/config.go, cmd/config_test.go
Empty string values for an envionment variable is a valid environment variable. This is used when
an application is reading for an environment variable present in the application's environment, but
does not necessarily care about the value.
fixes deis/deis#4802
=> feat(cmd): allow config:set FOO=""

cmd/apps.go, cmd/apps_test.go, cmd/cmd.go, cmd/labels.go, cmd/labels_test.go, deis.go, glide.lock, glide.yaml, parser/labels.go, parser/labels_test.go
Add Label model for workflow-cli new command Label.
Labels are general key value string to each app just for administration purpose.
Require https://github.com/deis/controller-sdk-go/pull/106
See https://github.com/deis/workflow/issues/597
=> feat(label-cmd): add Label cmd

Jenkinsfile
Our logic for discerning the [git branch](https://github.com/deis/workflow-cli/blob/master/Jenkinsfile#L55) was operating on the assumption that it would either be `remotes/origin/master` or a PR branch.  In fact, if the HEAD commit on the master branch is tagged, it will resolve to `tags/<tag>`.
As the logic above is used in many spots, this changes over to relying on `env.BRANCH_NAME`, which will be `master` even if tagged.  
Tested by porting this change manually to the master job to success: https://ci.deis.io/job/Deis/job/workflow-cli/job/master/173/ 
(With previous code, CI was executing logic on the assumption that it was a PR - kicking off pr test job, not building certain binaries, etc. - now we see it following the intended `master` path)
Fixes …
=> fix(Jenkinsfile): set git_branch to env.BRANCH_NAME

glide.lock, glide.yaml
Requires deis/workflow-e2e#347
=> chore(glide): update controller sdk to 9520b6c

cmd/healthchecks_test.go, parser/healthchecks.go, parser/healthchecks_test.go
=> fix(cmd): check for invalid probe types

cmd/cmd.go, cmd/config.go, cmd/config_test.go, parser/config.go, parser/config_test.go
closes #293 
Usage:
```
$ deis config:pull
$ diff <(deis config:list --diff) .env
$ vim .env
$ diff <(deis config:list --diff) .env
3c3
< HELLO=world
---
> HELLO=deis
```
=> feat(cmd): add config:list --diff

cmd/limits.go, cmd/limits_test.go, cmd/ps.go, cmd/ps_test.go
This fixes the proctype regex to match [the one used by deis/controller](https://github.com/deis/controller/blob/master/rootfs/api/serializers.py#L21).
This fixes an issue reported by @tylux on slack where setting limits for a proctype called "worker1" failed with:
```
Error: worker1=100M/350M doesn’t fit format type=#unit or type=# or type=#/#
```
I've also added a few test cases that check for good and bad proctypes.
=> fix(cmd) Fix proctype regex for setting limits

cmd/config.go, cmd/config_test.go
This adds a check to see if the value of SSH_KEY is already a Base64
encoded value, which is the case if "deis config:push" is used after
using "deis config:pull" on an app that already has SSH_KEY set.
This fixes #274.
=> feat(cmd): Support Base64 encoded SSH_KEY
