README.md

Depends on #6 for the go report card to successfully `go get` this project

doc(README.md): add travis and go report card badges

---

README.md

doc(README.md): make the travis badge point to workflow-cli

---

.travis.yml

And specify config file and user fields in quotes

fix(.travis.yml): fix bintray deploys

---

Makefile

so the glide cmd is run in-container

fix(Makefile): put test cmd in a new shell

---

README.md

doc(README): add instructions on installing

---

_scripts/generate-changelog.sh

There are no tags in the repo (yet), so I didn't actually start the CHANGELOG.md file.

feat(_scripts): add CHANGELOG.md generator script

---

cmd/registry.go
controller/api/config.go
controller/models/config/config_test.go
deis.go
parser/registry.go

ref https://github.com/deis/controller/pull/653

feat(registry): add support for setting private registry information per application

---

cmd/config.go

feat(config): ignore comments in config:push

---

cmd/apps.go

fix(apps:create): Better output when --no-remote used

---

cmd/keys.go
cmd/keys_test.go
controller/client/client.go
controller/client/client_test.go
controller/client/utils.go
controller/client/utils_test.go
pkg/git/git.go

ref(*): rewrite to use path/filepath for better OS compatibility

---

cmd/config.go

Updated `DEIS_RELEASE` to be `WORKFLOW_RELEASE` as done similarly elsewhere (see https://github.com/deis/workflow/pull/193)
Please make sure the below checklist is complete.

chore(cmd/config.go): DEIS_RELEASE -> WORKFLOW_RELEASE

---

cmd/limits.go

><> ./deis limits:set web=512Mi -a foo
Error: Error parsing limit web=512Mi: web=512Mi doesn't fit format type=#unit or type=#
Examples: web=2G worker=500M web=300
closes #61

fix(cmd): return error on bad limit parse

---

README.md

docs(README): add note to move binary elsewhere in PATH

---

deis.go

just a small nitpick that bothered me while trying to find commands. This alphabetizes the commands such that they are easier to grok.

style(deis.go): alphabetize commands

---

cmd/auth.go
cmd/certs.go
cmd/perms.go
cmd/utils.go
glide.lock
settings/settings.go

Updates to the latest version of the SDK, see deis/controller-sdk-go#9 for details about this particular update.

feat(*): update controller-go-sdk

---

cmd/keys.go
cmd/keys_test.go

fix(keys): fix range checks on input

---

cmd/auth.go
cmd/ps.go
glide.lock

feat(*): update sdk to use new error system.

---

deis.go

doc(deis): add "use deis help auth to learn more" help string

---

README.md

This got overlooked earlier 😭 and is no longer true.

fix(README): remove experimental windows support passage

---

cmd/apps.go
cmd/auth.go
cmd/builds.go
cmd/certs.go
cmd/config.go
cmd/domains.go
cmd/git.go
cmd/healthchecks.go
cmd/keys.go
cmd/limits.go
cmd/perms.go
cmd/ps.go
cmd/registry.go
cmd/releases.go
cmd/tags.go
cmd/users.go
cmd/utils.go
glide.lock
settings/settings.go
settings/settings_test.go

This complements deis/controller-sdk-go#16 by adding in a settings object to manage limits and usernames.

ref(settings): manage username and limits in settings

---

Jenkinsfile

The ref that jenkins checks out is different from the one I got locally, so it needs to be fixed.

fix(Jenkinsfile): fix incorrect master ref

---

cmd/ps.go
cmd/ps_test.go

fix(ps): give ps:restart a better understanding between RC and Deployment pods

---

Jenkinsfile

Branched from original PR https://github.com/deis/workflow-cli/pull/121

test(jenkins): trigger e2e tests after successful build

---

version/version.go

bump version to latest release

feat(version): bump version to v2.2.0

---

Jenkinsfile

per https://github.com/deis/controller-sdk-go/pull/46
Requires https://github.com/deis/workflow-cli/pull/138

ref(Jenkinsfile): remove sdk-related params and logic

---

cmd/config.go
cmd/registry.go
cmd/shortcuts.go
cmd/shortcuts_test.go

- fixes deis/workflow-e2e#243
- fix various gofmt errors

feat(shortcuts): add shortcuts test

---

Jenkinsfile

ref https://github.com/deis/controller-sdk-go/pull/50
cc @Joshua-Anderson

feat(Jenkinsfile): get actual PR commit, if PR

---

cmd/apps.go
cmd/git.go
parser/git.go
pkg/git/git.go

Requires workflow-e2e#278
Fixes #39

feat(git): add more flags to the git command

---

glide.lock
glide.yaml

Brings in saner APIMismatch behavior and an updated error message. All credit goes to @Joshua-Anderson.
Requires https://github.com/deis/controller#943

chore(glide): update controller-sdk-go

---

Jenkinsfile

Now that we print it in the build name as of https://github.com/deis/jenkins-jobs/pull/177/commits/91a0f45ee2488ee1534bcb1c27e6d2824ea54dbc

feat(Jenkinsfile): send COMPONENT_REPO param to e2e job

---

cmd/routing.go
glide.lock
glide.yaml

supercedes https://github.com/deis/workflow-cli/pull/170
see https://github.com/deis/controller-sdk-go/pull/73

ref(cmd): use api.NewRoutable() to instantiate Routable field

---

Jenkinsfile

fix(CI): don't cache latest binaries

---

Jenkinsfile

Closes https://github.com/deis/workflow-cli/issues/174

feat(Jenkinsfile): wipe vendor dir if bootstrap fails

---

Jenkinsfile

https://cloud.google.com/storage/docs/gsutil/addlhelp/WorkingWithObjectMetadata?hl=en_US#custom-metadata

feat(Makefile): add git branch and sha information to the uploaded blob

---

CONTRIBUTING.md

Hiya, the Troubleshooting URL was pointing to the wrong place.

Fix link to troubleshooting doc

---

Jenkinsfile

To avoid making changes, I'm going to start by uploading to both the `workflow-cli` bucket and then specific bucket. We can then start to migrate.
@vdice how do you propose looking up a revision for a CLI between the PR and master bucket in e2e? Try to download from master, and if that fails download from the PR bucket?

feat(CI): upload CLI to seperate buckets

---

cmd/maintenance.go
cmd/maintenance_test.go
cmd/routing.go
cmd/routing_test.go

Also add tests for the behavior. Fixes #189

fix(routing, maintenance): check for existence of pointer before reading it

---

Jenkinsfile

To use approach seen [here](https://github.com/jenkinsci/pipeline-examples/blob/master/pipeline-examples/gitcommit/gitcommit.groovy).

ref(Jenkinsfile): remove shell output hack

---

cmd/autoscale.go
cmd/autoscale_test.go
cmd/cmd.go
deis.go
glide.lock
glide.yaml
parser/autoscale.go

ref https://github.com/deis/controller-sdk-go/pull/89

feat(autoscale): add the ability to define autoscale rules per process type on an app

---

Jenkinsfile

I overlooked a few accidental global variables, so I fixed them up and CI should hopefully pass on master now.
cc @vdice

fix(CI): define more variables locally

---

glide.lock
glide.yaml

This updates the API version and fixes `deis logs`.

chore(glide): update Controller SDK

---

cmd/apps.go
cmd/apps_test.go
pkg/git/git.go

fix(cmd): fix help string when git remote already exists

---

cmd/apps.go
cmd/auth.go
cmd/autoscale.go
cmd/builds.go
cmd/certs.go
cmd/cmd.go
cmd/config.go
cmd/domains.go
cmd/git.go
cmd/healthchecks.go
cmd/keys.go
cmd/limits.go
cmd/maintenance.go
cmd/perms.go
cmd/ps.go
cmd/registry.go
cmd/releases.go
cmd/routing.go
cmd/shortcuts.go
cmd/tags.go
cmd/tls.go
cmd/users.go
cmd/utils.go
cmd/utils_test.go
cmd/version.go
cmd/whitelist.go

Also adds addational tests to the file.
Fixes #120

feat(cmd): only print version mismatch warning once

---

cmd/healthchecks.go
cmd/healthchecks_test.go
parser/healthchecks.go

fixes https://github.com/deis/controller/issues/1030

fix(healthcheck): show all the healthchecks set when no proctype is specified

---

Jenkinsfile

(Now that we can send notifications to specific/non-default channels)

feat(Jenkinsfile): send slack channel to downstream test job

---

cmd/ps.go
cmd/ps_test.go

ref https://github.com/deis/controller/pull/1132

fix(proctype): Change the regex used for validating proctypes

---

cmd/apps_test.go
cmd/labels.go
cmd/labels_test.go
glide.lock
glide.yaml

also ref https://github.com/deis/controller-sdk-go/pull/107

feat(cmd/labels.go): sort labels when listing

---

glide.lock
glide.yaml
parser/healthchecks.go
parser/healthchecks_test.go

fixes #279 
requires https://github.com/deis/controller-sdk-go/pull/110

fix(healthcheck): Parse arguments properly for httpheaders

---

glide.lock
glide.yaml

chore(glide): bump controller-sdk-go to 50747d7

---

Dockerfile

See https://github.com/deis/docker-go-dev/releases/tag/v0.22.0

chore(Dockerfile): update go-dev to v0.22.0
